CREATE TABLE IF NOT EXISTS Artists(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Genres(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL	
);

CREATE TABLE IF NOT EXISTS ArtistsGenres(
	ArtistId INTEGER REFERENCES Artists(Id) NOT NULL,
	GenresId INTEGER REFERENCES Genres(Id) NOT NULL
);

CREATE TABLE IF NOT EXISTS Albums(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	PublishedYear INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistsAlbum(
	ArtistId INTEGER REFERENCES Artists(Id) NOT NULL,
	AlbumId INTEGER REFERENCES Albums(Id) NOT NULL
);

CREATE TABLE IF NOT EXISTS Songs(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	Length INTEGER NOT NULL,
	AlbumId INTEGER REFERENCES Albums(Id) NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection(
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	PublishedYear INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS SongCollection(
	SongId INTEGER REFERENCES Songs(Id) NOT NULL,
	CollectionId INTEGER REFERENCES Collection(Id) NOT NULL
);

	
	
	